import { Card, CardContent, CardHeader, CardTitle } from "../../components/ui/card";
import { Badge } from "../../components/ui/badge";
import { Button } from "../../components/ui/button";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "../../components/ui/table";
import { Mail, Phone } from "lucide-react";

const mockLeads = [
  { id: "1", name: "John Anderson", phone: "+1 (555) 234-5678", classification: "Hot", interest: "Enterprise Plan", lastContact: "2026-03-06 14:30", score: 95 },
  { id: "2", name: "Sarah Mitchell", phone: "+1 (555) 987-6543", classification: "Hot", interest: "API Integration", lastContact: "2026-03-06 11:30", score: 92 },
  { id: "3", name: "Michael Chen", phone: "+1 (555) 321-0987", classification: "Hot", interest: "Premium Features", lastContact: "2026-03-05 16:20", score: 88 },
  { id: "4", name: "Emily Rodriguez", phone: "+1 (555) 876-5432", classification: "Warm", interest: "Pricing Info", lastContact: "2026-03-06 13:45", score: 75 },
  { id: "5", name: "David Kim", phone: "+1 (555) 456-7890", classification: "Warm", interest: "Demo Request", lastContact: "2026-03-06 10:15", score: 72 },
  { id: "6", name: "Lisa Johnson", phone: "+1 (555) 789-0123", classification: "Warm", interest: "General Info", lastContact: "2026-03-05 15:00", score: 68 },
  { id: "7", name: "Robert Taylor", phone: "+1 (555) 345-6789", classification: "Cold", interest: "Initial Inquiry", lastContact: "2026-03-06 12:00", score: 45 },
  { id: "8", name: "Jennifer White", phone: "+1 (555) 654-3210", classification: "Cold", interest: "Comparison", lastContact: "2026-03-06 09:45", score: 38 },
];

export default function Leads() {
  const getLeadColor = (classification: string) => {
    switch (classification) {
      case "Hot":
        return "bg-green-100 text-green-700";
      case "Warm":
        return "bg-yellow-100 text-yellow-700";
      case "Cold":
        return "bg-gray-100 text-gray-700";
      default:
        return "bg-gray-100 text-gray-700";
    }
  };

  const getScoreColor = (score: number) => {
    if (score >= 85) return "text-green-600";
    if (score >= 65) return "text-yellow-600";
    return "text-gray-600";
  };

  return (
    <div className="p-8 space-y-6">
      <div>
        <h1 className="text-3xl mb-2">Leads</h1>
        <p className="text-muted-foreground">Manage and track leads generated by your AI agent</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <Card>
          <CardContent className="pt-6">
            <p className="text-sm text-muted-foreground">Total Leads</p>
            <h3 className="text-3xl mt-2">142</h3>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <p className="text-sm text-muted-foreground">Hot Leads</p>
            <h3 className="text-3xl mt-2 text-green-600">34</h3>
            <p className="text-xs text-muted-foreground mt-1">23.9% conversion</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <p className="text-sm text-muted-foreground">Warm Leads</p>
            <h3 className="text-3xl mt-2 text-yellow-600">52</h3>
            <p className="text-xs text-muted-foreground mt-1">36.6% of total</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <p className="text-sm text-muted-foreground">Cold Leads</p>
            <h3 className="text-3xl mt-2 text-gray-600">56</h3>
            <p className="text-xs text-muted-foreground mt-1">39.4% of total</p>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Lead Database</CardTitle>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Name</TableHead>
                <TableHead>Phone</TableHead>
                <TableHead>Classification</TableHead>
                <TableHead>Interest</TableHead>
                <TableHead>Lead Score</TableHead>
                <TableHead>Last Contact</TableHead>
                <TableHead>Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {mockLeads.map((lead) => (
                <TableRow key={lead.id}>
                  <TableCell>{lead.name}</TableCell>
                  <TableCell className="font-mono text-sm">{lead.phone}</TableCell>
                  <TableCell>
                    <Badge className={getLeadColor(lead.classification)}>
                      {lead.classification}
                    </Badge>
                  </TableCell>
                  <TableCell>{lead.interest}</TableCell>
                  <TableCell>
                    <span className={`font-bold ${getScoreColor(lead.score)}`}>
                      {lead.score}
                    </span>
                  </TableCell>
                  <TableCell>{lead.lastContact}</TableCell>
                  <TableCell>
                    <div className="flex gap-2">
                      <Button size="sm" variant="outline">
                        <Phone className="h-4 w-4" />
                      </Button>
                      <Button size="sm" variant="outline">
                        <Mail className="h-4 w-4" />
                      </Button>
                    </div>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <Card>
          <CardHeader>
            <CardTitle className="text-lg">Top Hot Leads</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-3">
              {mockLeads.filter(l => l.classification === "Hot").slice(0, 3).map((lead) => (
                <div key={lead.id} className="flex items-center justify-between py-2 border-b last:border-0">
                  <div>
                    <p className="text-sm">{lead.name}</p>
                    <p className="text-xs text-muted-foreground">{lead.interest}</p>
                  </div>
                  <Badge className="bg-green-100 text-green-700">{lead.score}</Badge>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="text-lg">Recent Activity</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-3">
              <div className="text-sm">
                <p className="mb-1">3 new hot leads today</p>
                <p className="text-xs text-muted-foreground">+50% from yesterday</p>
              </div>
              <div className="text-sm">
                <p className="mb-1">12 calls converted to warm leads</p>
                <p className="text-xs text-muted-foreground">Average score: 72</p>
              </div>
              <div className="text-sm">
                <p className="mb-1">5 leads need follow-up</p>
                <p className="text-xs text-muted-foreground">Contacted &gt;24h ago</p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="text-lg">Lead Quality</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-3">
              <div>
                <div className="flex justify-between text-sm mb-2">
                  <span>Avg Lead Score</span>
                  <span className="font-bold">74</span>
                </div>
                <div className="w-full bg-gray-200 rounded-full h-2">
                  <div className="bg-primary h-2 rounded-full" style={{ width: "74%" }} />
                </div>
              </div>
              <div className="text-sm space-y-1">
                <p>Conversion Rate: <span className="font-bold">23.9%</span></p>
                <p>Response Time: <span className="font-bold">Instant</span></p>
                <p>Follow-up Rate: <span className="font-bold">92%</span></p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}