"""add face_encoding to student

Revision ID: 8e9cbf145d2f
Revises: 0001_initial_schema
Create Date: 2026-04-26 04:59:39.130858+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e9cbf145d2f'
down_revision: Union[str, None] = '0001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interaction_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=32), nullable=True),
    sa.Column('mode', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_logs_student_id'), 'interaction_logs', ['student_id'], unique=False)
    op.create_table('learning_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('preferred_language', sa.String(length=16), nullable=False),
    sa.Column('average_pace', sa.Float(), nullable=False, comment='Learning pace multiplier'),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('performance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=64), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('record_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_student_id'), 'performance', ['student_id'], unique=False)
    op.create_table('practice_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(length=128), nullable=False),
    sa.Column('was_correct', sa.Boolean(), nullable=False),
    sa.Column('hints_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_attempts_student_id'), 'practice_attempts', ['student_id'], unique=False)
    op.create_table('topic_mastery',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(length=128), nullable=False),
    sa.Column('mastery_level', sa.Float(), nullable=False, comment='Scale 0.0 to 1.0'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_mastery_student_id'), 'topic_mastery', ['student_id'], unique=False)
    op.alter_column('attendance', 'status',
               existing_type=sa.VARCHAR(length=16),
               comment="'present' or 'late'.",
               existing_nullable=False)
    op.alter_column('attendance', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='LBPH confidence score (lower = better match).',
               existing_nullable=True)
    op.alter_column('attendance', 'bounding_box',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Face bounding box as {x, y, w, h} in image pixels.',
               existing_nullable=True)
    op.drop_index('uix_attendance_session_student', table_name='attendance', postgresql_where='((session_id IS NOT NULL) AND (student_id IS NOT NULL))')
    op.create_index('ix_attendance_created_at', 'attendance', ['created_at'], unique=False)
    op.create_unique_constraint('uq_attendance_session_student', 'attendance', ['session_id', 'student_id'])
    op.alter_column('sessions', 'session_id',
               existing_type=sa.VARCHAR(length=128),
               comment='Composite human-readable session identifier.',
               existing_nullable=False)
    op.alter_column('sessions', 'period_number',
               existing_type=sa.INTEGER(),
               comment='1-indexed period number within the day (derived from timetable).',
               existing_nullable=True)
    op.alter_column('sessions', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment="'active' while the period runs; 'completed' afterwards.",
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.create_index(op.f('ix_sessions_date'), 'sessions', ['date'], unique=False)
    op.add_column('students', sa.Column('face_encoding', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='128-d face embedding vector for face_recognition library.'))
    op.alter_column('students', 'student_id',
               existing_type=sa.VARCHAR(length=64),
               comment="School-issued student identifier, e.g. 'S1001'.",
               existing_nullable=False)
    op.alter_column('students', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Full display name.',
               existing_nullable=False)
    op.alter_column('students', 'label_id',
               existing_type=sa.INTEGER(),
               comment='LBPH integer label. NULL until at least one face image is enrolled.',
               existing_nullable=True)
    op.alter_column('students', 'class_section',
               existing_type=sa.VARCHAR(length=64),
               comment="Class + section string, e.g. '10-A'.",
               existing_nullable=True)
    op.alter_column('students', 'active',
               existing_type=sa.BOOLEAN(),
               comment='Soft-delete flag. Inactive students are excluded from recognition.',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint('students_student_id_key', 'students', type_='unique')
    op.drop_index('ix_students_student_id', table_name='students')
    op.create_index(op.f('ix_students_student_id'), 'students', ['student_id'], unique=True)
    op.alter_column('timetable', 'day_of_week',
               existing_type=sa.VARCHAR(length=16),
               comment="Lowercase English day name, e.g. 'monday'.",
               existing_nullable=False)
    op.alter_column('timetable', 'period_number',
               existing_type=sa.INTEGER(),
               comment='1-indexed period number within the day (1–8).',
               existing_nullable=False)
    op.create_index('ix_timetable_class_day', 'timetable', ['class_section', 'day_of_week'], unique=False)
    op.create_unique_constraint('uq_timetable_class_day_period', 'timetable', ['class_section', 'day_of_week', 'period_number'])
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=32),
               comment="'admin', 'teacher', or 'robot'.",
               existing_nullable=False,
               existing_server_default=sa.text("'teacher'::character varying"))
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment="'admin', 'teacher', or 'robot'.",
               existing_nullable=False,
               existing_server_default=sa.text("'teacher'::character varying"))
    op.drop_constraint('uq_timetable_class_day_period', 'timetable', type_='unique')
    op.drop_index('ix_timetable_class_day', table_name='timetable')
    op.alter_column('timetable', 'period_number',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='1-indexed period number within the day (1–8).',
               existing_nullable=False)
    op.alter_column('timetable', 'day_of_week',
               existing_type=sa.VARCHAR(length=16),
               comment=None,
               existing_comment="Lowercase English day name, e.g. 'monday'.",
               existing_nullable=False)
    op.drop_index(op.f('ix_students_student_id'), table_name='students')
    op.create_index('ix_students_student_id', 'students', ['student_id'], unique=False)
    op.create_unique_constraint('students_student_id_key', 'students', ['student_id'])
    op.alter_column('students', 'active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Soft-delete flag. Inactive students are excluded from recognition.',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('students', 'class_section',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment="Class + section string, e.g. '10-A'.",
               existing_nullable=True)
    op.alter_column('students', 'label_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='LBPH integer label. NULL until at least one face image is enrolled.',
               existing_nullable=True)
    op.alter_column('students', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Full display name.',
               existing_nullable=False)
    op.alter_column('students', 'student_id',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment="School-issued student identifier, e.g. 'S1001'.",
               existing_nullable=False)
    op.drop_column('students', 'face_encoding')
    op.drop_index(op.f('ix_sessions_date'), table_name='sessions')
    op.alter_column('sessions', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment="'active' while the period runs; 'completed' afterwards.",
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('sessions', 'period_number',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='1-indexed period number within the day (derived from timetable).',
               existing_nullable=True)
    op.alter_column('sessions', 'session_id',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='Composite human-readable session identifier.',
               existing_nullable=False)
    op.drop_constraint('uq_attendance_session_student', 'attendance', type_='unique')
    op.drop_index('ix_attendance_created_at', table_name='attendance')
    op.create_index('uix_attendance_session_student', 'attendance', ['session_id', 'student_id'], unique=True, postgresql_where='((session_id IS NOT NULL) AND (student_id IS NOT NULL))')
    op.alter_column('attendance', 'bounding_box',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Face bounding box as {x, y, w, h} in image pixels.',
               existing_nullable=True)
    op.alter_column('attendance', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='LBPH confidence score (lower = better match).',
               existing_nullable=True)
    op.alter_column('attendance', 'status',
               existing_type=sa.VARCHAR(length=16),
               comment=None,
               existing_comment="'present' or 'late'.",
               existing_nullable=False)
    op.drop_index(op.f('ix_topic_mastery_student_id'), table_name='topic_mastery')
    op.drop_table('topic_mastery')
    op.drop_index(op.f('ix_practice_attempts_student_id'), table_name='practice_attempts')
    op.drop_table('practice_attempts')
    op.drop_index(op.f('ix_performance_student_id'), table_name='performance')
    op.drop_table('performance')
    op.drop_table('learning_profiles')
    op.drop_index(op.f('ix_interaction_logs_student_id'), table_name='interaction_logs')
    op.drop_table('interaction_logs')
    # ### end Alembic commands ###
